version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        ports:
            - "808:80"
        depends_on:
            - nopcommerce_database
    nopcommerce_database:
        image: "mysql:latest"
        container_name: nopcommerce_mysql_server
        command: "--default-authentication-plugin=mysql_native_password"
        restart: "always"
        ports: 
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: "zaQ@1234xsW"

volumes:
  nopcommerce_data:            